#!/bin/bash

config="${XDG_CONFIG_HOME:-~/.config}/spcli.conf"

if [ ! -f "$config" ]; then
	echo "Config file does not exist!"
	exit 1
fi

source "$config"

#
# cURL
#

function req_get(){
	curl --fail -sL -H "Authorization: ${TOKEN}" "https://api.apparyllis.com/v1/${1}"
	if [ $? -ne 0 ]; then
		echo "GET request to ${1} failed."
		exit 1
	fi
}

function req_post(){
	curl --fail -sL -X POST -H "Authorization: ${TOKEN}" -H "Content-Type: application/json" "https://api.apparyllis.com/v1/${1}" --data-raw "${2}"
	if [ $? -ne 0 ]; then
		echo "POST request to ${1} with data '${2}' failed."
		exit 1
	fi
}

function req_patch(){
	curl --fail -sL -X PATCH -H "Authorization: ${TOKEN}" -H "Content-Type: application/json" "https://api.apparyllis.com/v1/${1}" --data-raw "${2}"
	if [ $? -ne 0 ]; then
		echo "PATCH request to ${1} with data '${2}' failed."
		exit 1
	fi
}

#
# API
#

function getFriendFronters(){
	local _user=$(req_get "user/$1")
	local _fronting=$(req_get "friend/$1/getFront")
	local _userName=$(jq -r ".content.username" <<< "$_user")

	local _members=$(req_get "members/$1")
	local _customFronts=$(req_get "customFronts/$1")

	echo "Currently fronting at $_userName:"

	while read -r fronter; do
		local name=$(jq -r ".[] | select(.id == \"$fronter\") | .content.name" <<< "$_members")

		if [ -z "$name" ]; then
			name=$(jq -r ".[] | select(.id == \"$fronter\") | .content.name" <<< "$_customFronts")
		fi

		local status=$(jq -r ".statuses[\"$fronter\"]" <<< "$_fronting")

		if [ "$status" = "null" ]; then
			echo "${name}"
		else
			echo "${name}: ${status}"
		fi
	done < <(jq -r ".fronters[]" <<< "$_fronting")
}

function getFronting(){
	local _me=$(req_get "me" | jq -r ".id")
	local _fronting=$(req_get "fronters")
	local _members=$(req_get "members/$_me")
	local _customFronts=$(req_get "customFronts/$_me")

	echo "Currently fronting:"

	while read -r fronter; do
		local name=$(jq -r ".[] | select(.id == \"$fronter\") | .content.name" <<< "$_members")

		if [ -z "$name" ]; then
			name=$(jq -r ".[] | select(.id == \"$fronter\") | .content.name" <<< "$_customFronts")
		fi

		local status=$(jq -r ".[] | select(.content.member == \"$fronter\") | .content.customStatus" <<< "$_fronting")
		local date=$(jq -r ".[] | select(.content.member == \"$fronter\") | .content.startTime | . / 1000 | \"@\\(.)\"" <<< "$_fronting" | date +"%c" -f -)

		if [ "$status" = "null" ]; then
			echo "${name} - ${date}"
		else
			echo "${name}: ${status} - ${date}"
		fi
	done < <(jq -r ".[] | .content.member" <<< "$_fronting")
}

function addFront(){
	local _member="$1"
	local _starttime=$(date +%s%3N)

	local result=$(req_post "frontHistory/" "{\"custom\":false,\"startTime\":$_starttime,\"member\":\"$_member\",\"live\":true}" | jq -r .)

	echo "Added $1 to front. Fronting History ID: $result"
}

function removeFront(){
	local _member="$1"
	local _endtime=$(date +%s%3N)
	local _docId=$(req_get "frontHistory/member/$_member" | jq -r ".[] | select(.content.member == \"$_member\" and .content.live == true) | .id")

	local result=$(req_patch "frontHistory/$_docId" "{\"live\":false,\"endTime\":$_endtime,\"member\":\"$_member\"}")

	echo "Removed $1 from front."
}

function setFront(){
	local _fronting=$(req_get "fronters")
	while read -r fronter; do
		removeFront "$fronter"
	done < <(jq -r ".[] | .content.member" <<< "$_fronting")
	addFront "$1"
}

function setCustomStatus(){
	local _member="$1"
	local _customStatus="$2"
	local _docId=$(req_get "frontHistory/member/$_member" | jq -r ".[] | select(.content.member == \"$_member\" and .content.live == true) | .id")

	local result=$(req_patch "frontHistory/$_docId" "{\"member\":\"$_member\",\"customStatus\":\"$_customStatus\"}")

	echo "Custom status set to:" $2
}

#
# Plumbing
#

case $1 in
	friends)
		if [ -n "${users[$2]}" ]; then
			getFriendFronters "${users[$2]}"
			exit 0
		fi
		getFriendFronters "$2"
		exit 0
		;;
	fronts)
		getFronting
		exit 0
		;;
	add)
		if [ -n "${members[$2]}" ]; then
			addFront "${members[$2]}"
			exit 0
		fi
		addFront "$2"
		exit 0
		;;
	remove)
		if [ -n "${members[$2]}" ]; then
			removeFront "${members[$2]}"
			exit 0
		fi
		removeFront "$2"
		exit 0
		;;
	set)
		if [ -n "${members[$2]}" ]; then
			setFront "${members[$2]}"
			exit 0
		fi
		setFront "$2"
		exit 0
		;;
	status)
		if [ -n "${members[$2]}" ]; then
			setCustomStatus "${members[$2]}" "$3"
			exit 0
		fi
		setCustomStatus "$2" "$3"
		exit 0
		;;
esac
